import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Send, Clipboard, BrainCircuit, MessageCircle, BarChart3, Video, Clock } from 'lucide-react';
import LoadingSpinner from '../components/LoadingSpinner';
import { useAnalysisData, useAnalysisMutation, useAllAnalysisData } from '../hooks/useAnalysis';
import { showSuccessToast, showInfoToast, toastMessages } from '../utils/toastConfig';

interface AnalysisResult {
  themes: string[];
  pain_points: string[];
  video_ideas: { title: string; hook: string }[];
}

export default function DashboardPage() {
  const [searchParams] = useSearchParams();
  const [url, setUrl] = useState(searchParams.get('url') || '');
  const [currentAnalysis, setCurrentAnalysis] = useState<AnalysisResult | null>(null);
  
  // Get cached data for current URL (doesn't trigger API)
  const { data: cachedData } = useAnalysisData(url);
  
  // Get all cached analysis data
  const { data: allCachedData, refetch: refetchAllData } = useAllAnalysisData();
  
  // Mutation for manual API calls
  const analysisMutation = useAnalysisMutation();

  // Check for cached data on component mount and URL change
  useEffect(() => {
    if (url && cachedData) {
      setCurrentAnalysis(cachedData);
      showInfoToast(toastMessages.showingCached);
    } else if (!url) {
      // If no URL, try to show the most recent analysis
      refetchAllData().then(({ data }) => {
        if (data && data.length > 0) {
          setCurrentAnalysis(data[0].data);
          setUrl(data[0].url);
          showInfoToast(toastMessages.showingRecent);
        }
      });
    }
  }, [url, cachedData]);

  const handleAnalysis = async (targetUrl: string) => {
    if (!targetUrl.trim()) return;

    try {
      const result = await analysisMutation.mutateAsync(targetUrl);
      setCurrentAnalysis(result);
      showSuccessToast(toastMessages.analysisComplete);
    } catch (error) {
      // Error handling is done in the mutation hook
      console.error("Analysis failed", error);
    }
  };

  const handleUrlChange = (newUrl: string) => {
    setUrl(newUrl);
    // Check if we have cached data for this URL
    if (newUrl) {
      // The useEffect will handle showing cached data
    } else {
      setCurrentAnalysis(null);
    }
  };

  const handleCopyToNotion = (idea: any) => {
    const markdown = `
# Content Idea: ${idea.title}
**Hook:** ${idea.hook}
---
*Generated by Previda*
  `;
    navigator.clipboard.writeText(markdown);
    showSuccessToast(toastMessages.copiedToNotion);
  };

  const loading = analysisMutation.isPending;

  return (
    <div className="p-3 sm:p-6 max-w-7xl mx-auto pt-20 sm:pt-24">
      {/* Search Header */}
      <div className="glass p-3 sm:p-4 rounded-xl sm:rounded-2xl mb-6 sm:mb-8 flex flex-col sm:flex-row gap-3 sm:gap-4 border-2 border-white/10">
        <input 
          className="bg-transparent grow px-3 sm:px-4 py-2 sm:py-0 outline-none text-base sm:text-lg rounded-lg sm:rounded-none border sm:border-0 border-white/20 sm:border-transparent"
          placeholder="Analyze another video..."
          value={url}
          onChange={(e) => handleUrlChange(e.target.value)}
        />
        <button 
          onClick={() => handleAnalysis(url)}
          disabled={!url.trim() || loading}
          className="neo-btn bg-neon-green text-black font-black px-4 sm:px-6 py-2 rounded-lg flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed text-sm sm:text-base"
        >
          {loading ? 'MINING...' : 'RUN AI'} <Send size={16} className="sm:w-[18px] sm:h-[18px]" />
        </button>
      </div>

      {/* Show cached data indicator */}
      {currentAnalysis && cachedData && !loading && (
        <div className="mb-4 p-3 bg-neon-green/10 border border-neon-green/20 rounded-lg flex items-center gap-2 text-neon-green text-xs sm:text-sm">
          <Clock size={14} className="sm:w-4 sm:h-4 flex-shrink-0" />
          <span>Showing cached results. Click "RUN AI" to refresh.</span>
        </div>
      )}

      {loading ? (
        <LoadingSpinner />
      ) : currentAnalysis ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
          {/* Main Ideas - Large Card */}
          <div className="lg:col-span-2 glass p-4 sm:p-8 rounded-2xl sm:rounded-3xl border-2 border-white/10 shadow-neo">
            <h2 className="text-xl sm:text-3xl font-black mb-4 sm:mb-6 flex items-center gap-2">
              <BrainCircuit className="text-electric-purple w-6 h-6 sm:w-8 sm:h-8" /> 
              <span className="text-base sm:text-3xl">Video Ideas & Outlines</span>
            </h2>
            <div className="space-y-4 sm:space-y-6">
              {currentAnalysis.video_ideas.map((idea, i) => (
                <div key={i} className="bg-white/5 p-4 sm:p-6 rounded-xl sm:rounded-2xl border border-white/5 group relative">
                  <h4 className="text-lg sm:text-xl font-bold text-neon-green mb-2">{idea.title}</h4>
                  <p className="text-gray-400 mb-3 sm:mb-4 italic text-sm sm:text-base">"{idea.hook}"</p>
                  <button 
                    className="text-xs sm:text-sm flex items-center gap-1 text-electric-purple font-bold opacity-100 sm:opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                    onClick={() => handleCopyToNotion(idea)}
                  >
                    <Clipboard size={12} className="sm:w-[14px] sm:h-[14px]" /> COPY TO NOTION
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Sentiment & Themes */}
          <div className="space-y-4 sm:space-y-6">
            <div className="glass p-4 sm:p-6 rounded-2xl sm:rounded-3xl border-2 border-neon-green/20 shadow-neo-green">
              <h3 className="font-black mb-3 sm:mb-4 flex items-center gap-2 text-sm sm:text-base">
                <BarChart3 size={16} className="sm:w-5 sm:h-5"/> What They're Talking About
              </h3>
              <div className="flex flex-wrap gap-2">
                {currentAnalysis.themes.map((theme, i) => (
                  <span key={i} className="bg-neon-green/10 text-neon-green px-2 sm:px-3 py-1 rounded-full text-xs sm:text-sm font-bold border border-neon-green/20">
                    #{theme}
                  </span>
                ))}
              </div>
            </div>

            <div className="glass p-4 sm:p-6 rounded-2xl sm:rounded-3xl border-2 border-electric-purple/20 shadow-neo-purple">
              <h3 className="font-black mb-3 sm:mb-4 flex items-center gap-2 text-sm sm:text-base">
                <MessageCircle size={16} className="sm:w-5 sm:h-5"/> The Struggle (Viewer Problems)
              </h3>
              <ul className="space-y-2 sm:space-y-3">
                {currentAnalysis.pain_points.map((point, i) => (
                  <li key={i} className="text-gray-400 text-xs sm:text-sm flex items-start gap-2">
                    <span className="text-electric-purple flex-shrink-0">•</span> 
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="text-center py-12 sm:py-20 opacity-30">
          <Video size={60} className="sm:w-20 sm:h-20 mx-auto mb-4" />
          <p className="text-lg sm:text-2xl font-black px-4">PASTE A LINK TO BEGIN THE MINING PROCESS</p>
          
          {/* Show recent analyses if available */}
          {allCachedData && allCachedData.length > 0 && (
            <div className="mt-6 sm:mt-8 px-4">
              <p className="text-sm sm:text-lg mb-3 sm:mb-4 opacity-70">Or continue with recent analyses:</p>
              <div className="flex flex-col sm:flex-row flex-wrap gap-2 justify-center">
                {allCachedData.slice(0, 3).map((item, i) => (
                  <button
                    key={i}
                    onClick={() => {
                      setUrl(item.url);
                      setCurrentAnalysis(item.data);
                    }}
                    className="px-3 sm:px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-xs sm:text-sm border border-white/10 hover:border-white/20 transition-all"
                  >
                    {item.url.length > 30 ? `${item.url.substring(0, 30)}...` : item.url}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}